### ISSUE TITLE
Missing mount of /tmp/.ssh folder

### ISSUE THREAD

**Issue by jost-kuenzel** [frgmt/vagrant-invade#2]
Hey frgmt. First thanks for this nice plugin. 
Migrating from the old invade system I discovered that currently the /tmp/.ssh is not mounted. And I cannot define the mount in the 'synced_folder' as the key 'nfs' is already defined for the project folder.
/tmp/.ssh is needed for https://gitlab.innogames.de/backend/puppet-ssh.
A suggestion I have is to use the key as a name with meaning rather that as the filesystem type.
So instead of e.g.

``` yml
    synced_folder:
      nfs:
        name: 'www'
        path: '/www'
        source: '..'
        mount_options:
          - nolock
```

it could be

``` yml
    synced_folder:
      www:
        type: 'nfs'
        path: '/www'
        source: '..'
        mount_options:
          - nolock
```

I'd be happy to hear your opinion on this.
